# This is a basic workflow to help you get started with Actions

name: crates.io

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: publish dry-run
      run: cargo publish --dry-run --verbose
